name: "Check basic style"
description: >
  Check basic file properties like UTF-8 encoding, trailing whitespace, a max line length, ...
author: "LukasKalbertodt"

inputs:
  files:
    description: >
      List of files to check. Supports wildcards. For more information on the
      allowed patterns, see: https://www.npmjs.com/package/glob
    required: false
    default: "**"
  check_generated_files:
    description: >
      By default, some files like 'Cargo.lock', 'package-lock.json', ... are not
      checked. Setting this to `true` disables this ignoring.
    required: false
    default: false
  single_trailing_newline:
    description: "Make sure files end with a single trailing newline"
    required: false
    default: "true"
  no_trailing_whitespace:
    description: "Make sure there is no whitespace at the very end of a line"
    required: false
    default: "true"
  max_line_len:
    description: >
      The maximum number of Unicode code points a line may have. Set to -1 to disable check.
    required: false
    default: "100"
  allow_long_lines_with_urls:
    description: >
      Lines longer than 'max_line_len' are allowed if they contain something
      that looks like a "common" URL. Not all of URL syntax is allowed, just
      common cases.
    required: false
    default: "true"
  no_tabs:
    description: Disallow any tab characters ('\t') anywhere
    required: false
    default: "true"

runs:
  using: "node16"
  main: "dist/index.js"
