name: "Check basic file properties"
description: "Check basic properties like files being UTF-8, a max line length,"
author: "LukasKalbertodt"
inputs:
  files:
    description: "List of files to check. Supports wildcards. If not set, defaults to checking TODO"
    required: false
  assert_single_trailing_newline:
    description: "Make sure files end with a single trailing newline"
    required: false
    default: "true"
  assert_no_trailing_whitespace:
    description: "Make sure there is no whitespace at the very end of a line"
    required: false
    default: "true"
  max_line_len:
    description: >
      The maximum number of Unicode code points a line may have. Set to -1 to disable check.
    required: false
    default: "100"
  allow_long_lines_with_urls:
    description: >
      Lines longer than 'max_line_len' are allowed if they contain something
      that looks like a "common" URL. Not all of URL syntax is allowed, just
      common cases.
    required: false
    default: "true"
  disallow_tabs:
    description: Disallow any tab characters ('\t') anywhere
    required: false
    default: "true"

runs:
  using: "node16"
  main: "dist/index.js"
