name: "Check basic file properties"
description: "Check basic properties like files being UTF-8, a max line length,"
author: "LukasKalbertodt"
inputs:
  files:
    description: "List of files to check. Supports wildcards. If not set, defaults to checking TODO"
    required: false
  assert_single_trailing_newline:
    description: "Make sure files end with a single trailing newline"
    required: false
    default: "true"
  assert_no_trailing_whitespace:
    description: "Make sure there is no whitespace at the very end of a line"
    required: false
    default: "true"

runs:
  using: "node16"
  main: "dist/index.js"
