name: Check code
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build:prod
      - name: Make sure `dist` is up to date
        run: git diff --exit-code dist/

